services:
  - type: web
    name: lantercar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: lantercar-db
          property: connectionString

databases:
  - name: lantercar-db
    databaseName: lantercar
    user: lantercar_user

